### ISSUE TITLE
[Home page] Sign-up link does not pop up after already clicked

### ISSUE THREAD

**Issue by panda6868** [zmtnda/pamelo#18]
Step to reproduce:
1) GO to home page
2) Click on the signup link (the sign-up pop up window will pops up)
3) Click outside the window to exit
4) Click back on the sign-up link

What happened:
The sign-up pop up window does not show again

What's expected: The pop up window should pop up every time you click on the link

**Comment by leopangchan** [comment]
Another way to reproduce:
1. click sign up on the homepage.
2. click sign up without filling in any fields.
3. exit pop-up.
4. click sign up on the homepage again.

Same bug happen after step 4.
