### ISSUE TITLE
[Customer] serviceName not shown

### ISSUE THREAD

**Issue by zmtnda** [zmtnda/pamelo#31]
What to do:
1. log in as cust1@11.com
2. click order
3. choose service
4. service name not shown.

**Comment by sbilich** [comment]
@zmtnda I just realized that we don't even need to show the service name because they already know what it is because they select the service name in the drop-down list. It would be more useful to include the technician's name.

**Comment by zmtnda** [comment]
@sbilich Yes. you are right. Can you just include technician name and the amount as well?

**Comment by leopangchan** [comment]
cool!
