### ISSUE TITLE
[UI] Change Color scheme

### ISSUE THREAD

**Issue by sbilich** [zmtnda/pamelo#50]
The current color scheme doesn't fit, we need to discuss and implement a color scheme that reflects the application better.

- white background
- bright colors for the buttons, tabs, and navigation bar.

**Comment by panda6868** [comment]
I agree. This issue however need to go in agreement with the whole team though! Since really not any of us are in role UI/UX design anymore, I think we should have a group meeting to agree on the color scheme and the picture on home page as well. It is so ugly rn.

**Comment by leopangchan** [comment]
Following this template right now.
https://blackrockdigital.github.io/startbootstrap-stylish-portfolio/
