### ISSUE TITLE
[UI][Customer] Customer Order History table too wide

### ISSUE THREAD

**Issue by sbilich** [zmtnda/pamelo#51]
The Order History table is too wide for the page and should be adjusted to fit into the space left next to the user navigation bar on the left side of the page. 

- The table should auto-fit into the view
- should adjust size based off of the browser's dimensions

**Comment by leopangchan** [comment]
I'm working styling all tables on all webpages.

![image](https://cloud.githubusercontent.com/assets/16515271/20466969/bf013fbe-af31-11e6-8ee8-c3ff20691d88.png)
