### ISSUE TITLE
[Customer.template.html] DropDown services on

### ISSUE THREAD

**Issue by zmtnda** [zmtnda/pamelo#6]
What to do:
1. Create a table called services_offer that simply has ID and serviceName
2. The drop down list query services_offer table and show all the services
3. Once user pick the services will query selectServiceName == services.name 
4. It will then show all the technicians who offer that services with the price in ascending order

Front End Team:
Work on modifying the UI

Back End Team:
Work on nodejs Serivces.js

**Comment by leopangchan** [comment]
Feature Sign-off sheet:
1. Code Review:
2. Documentation:
3. Tested:
