### ISSUE TITLE
[Customer] Can't Order Services that are #2 or greater in the list

### ISSUE THREAD

**Issue by sbilich** [zmtnda/pamelo#77]
On the Order page of the customer page, if the user tries to order a service that isn't first in the list of available services an error is thrown:
<img width="1079" alt="screen shot 2016-11-28 at 5 05 13 pm" src="https://cloud.githubusercontent.com/assets/11725482/20692852/6e0d0368-b58f-11e6-9fb0-99f1c95cedf9.png">

**Comment by zmtnda** [comment]
@sbilich good find. :)
